language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: XPIKS_BINARY=binary
    - os: linux
      dist: trusty
      sudo: required
      env: CORE_TESTS=tests QT_FATAL_WARNINGS=true
    - os: linux
      dist: trusty
      sudo: required
      env: INTEGRATION_TESTS=tests QT_FATAL_WARNINGS=true
    - os: linux
      dist: trusty
      sudo: required
      env: UI_TESTS=tests QT_FATAL_WARNINGS=true
      
git:
  depth: 3

cache:
  apt: true
  directories:
    - my-apt-cache

install:
  - ./scripts/ci/install-${TRAVIS_OS_NAME}.sh
  - . ./scripts/ci/env-${TRAVIS_OS_NAME}.sh

before_script:
  - ulimit -c unlimited -S       # enable core dumps
  - if [ -n "$UI_TESTS" ]; then export DISPLAY=:99.0; fi
  - if [ -n "$UI_TESTS" ]; then sh -e /etc/init.d/xvfb start; fi
  - if [ -n "$UI_TESTS" ]; then sleep 3; fi # give xvfb some time to start
  - git fetch origin gh-pages
  - git checkout FETCH_HEAD -- api

script:
  - ${TRAVIS_BUILD_DIR}/scripts/build/build_vendors_linux.sh travis-ci
  - ls -la libs/*
  - if [ -n "$XPIKS_BINARY" ]; then "$TRAVIS_BUILD_DIR/scripts/ci/travis-ci-xpiks.sh"; fi
  - if [ -n "$CORE_TESTS" ]; then "$TRAVIS_BUILD_DIR/scripts/ci/travis-ci-core-tests.sh"; fi
  - if [ -n "$INTEGRATION_TESTS" ]; then "$TRAVIS_BUILD_DIR/scripts/ci/travis-ci-integration-tests.sh"; fi
  - if [ -n "$UI_TESTS" ]; then "$TRAVIS_BUILD_DIR/scripts/ci/travis-ci-ui-tests.sh"; fi

